# packages in environment at /homes/ac.cesarasa/miniconda3/envs/DualGCN36GPU:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
absl-py                   1.4.0                    pypi_0    pypi
astor                     0.8.1                    pypi_0    pypi
astropy                   4.1                      pypi_0    pypi
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
cached-property           1.5.2                    pypi_0    pypi
candle                    0.0.1                    pypi_0    pypi
certifi                   2016.9.26                py36_0    conda-forge
charset-normalizer        2.0.12                   pypi_0    pypi
cudatoolkit               10.0.130                      0    anaconda
cudnn                     7.6.5                cuda10.0_0    anaconda
cycler                    0.11.0                   pypi_0    pypi
dataclasses               0.8                      pypi_0    pypi
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
deepchem                  2.4.0                    pypi_0    pypi
dill                      0.3.4                    pypi_0    pypi
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
gast                      0.5.3                    pypi_0    pypi
grpcio                    1.48.2                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
hickle                    5.0.2                    pypi_0    pypi
idna                      3.4                      pypi_0    pypi
importlib-metadata        4.8.3                    pypi_0    pypi
importlib-resources       5.4.0                    pypi_0    pypi
ipykernel                 5.5.5            py36hcb3619a_0    conda-forge
ipython                   5.8.0                    py36_1    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
joblib                    1.1.1                    pypi_0    pypi
jupyter_client            5.3.4                    py36_0    conda-forge
jupyter_core              4.5.0                      py_0    conda-forge
keras                     2.1.4                    pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.3.1                    pypi_0    pypi
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libsqlite                 3.40.0               h753d276_0    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
markdown                  3.3.7                    pypi_0    pypi
matplotlib                3.3.4                    pypi_0    pypi
mock                      5.0.1                    pypi_0    pypi
ncurses                   6.3                  h27087fc_1    conda-forge
numpy                     1.19.5                   pypi_0    pypi
openssl                   1.1.1t               h0b41bf4_0    conda-forge
pandas                    1.1.5                    pypi_0    pypi
patsy                     0.5.3                    pypi_0    pypi
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.4.0                    pypi_0    pypi
pip                       20.0.2                   py36_1    conda-forge
prompt_toolkit            1.0.15                     py_1    conda-forge
protobuf                  3.19.0                   pypi_0    pypi
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pygments                  2.12.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9                    pypi_0    pypi
python                    3.6.15          hb7a2778_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.6                     2_cp36m    conda-forge
pytz                      2022.7.1                 pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     19.0.2           py36h9947dbf_2    conda-forge
readline                  8.2                  h8228510_1    conda-forge
requests                  2.27.1                   pypi_0    pypi
scikit-learn              0.24.2                   pypi_0    pypi
scipy                     1.5.4                    pypi_0    pypi
setuptools                49.6.0           py36h5fab9bb_3    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.40.0               h4ff8645_0    conda-forge
statsmodels               0.12.2                   pypi_0    pypi
tensorboard               1.13.1                   pypi_0    pypi
tensorflow-estimator      1.13.0                   pypi_0    pypi
tensorflow-gpu            1.13.1                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tk                        8.6.12               h27826a3_0    conda-forge
tornado                   6.1              py36h8f6f2f9_1    conda-forge
tqdm                      4.64.1                   pypi_0    pypi
traitlets                 4.3.3              pyhd8ed1ab_2    conda-forge
typing-extensions         4.1.1                    pypi_0    pypi
urllib3                   1.26.15                  pypi_0    pypi
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
werkzeug                  2.0.3                    pypi_0    pypi
wheel                     0.34.2                   py36_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zeromq                    4.3.4                h9c3ff4c_1    conda-forge
zipp                      3.6.0                    pypi_0    pypi
zlib                      1.2.13               h166bdaf_4    conda-forge
